sudo: false
language: python
services:
  - docker
python:
  - "3.7"
branches:
  only:
    - master
install:
  - cd backend
  - mv backend/settings/example.py backend/settings/local.py
  - cd ..
  - mv db/.env.example db/.env
  - mv frontend/.env.docker.example frontend/.env
  - docker-compose up -d
  - bash -c "./backend/wait-for-it.sh localhost:5551"
before_script:
  - docker container ps
  - docker-compose exec worker flake8 "." "--statistics"
  - docker-compose exec worker coverage "erase"
script: docker-compose exec worker coverage "run" "manage.py" "test"
after_success:
  - docker-compose exec worker codecov
