sudo: false
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - cd backend
branches:
  only:
    - master
before_script:
  - flake8 backend/
script: python manage.py test