sudo: false
language: python
services:
  - postgresql
python:
  - "3.7"
env:
  - DJANGO_DEBUG_LOCAL=True
install:
  - cd backend
  - pip install -r requirements.txt
  - mv backend/settings/example.py backend/settings/local.py
  - cd ..
branches:
  only:
    - master
before_script:
  - psql -c "CREATE USER django_user WITH PASSWORD 'localpassword' CREATEDB;" -U postgres
  - flake8 backend/ --statistics
  - cd backend/
  - coverage erase
script: coverage run manage.py test -v 2
after_success:
  - codecov
