version: '3'

services:

    db:
        image: postgres
        container_name: postgresDB
        env_file:
            - ./db/.env
        volumes:
            - "postgres-data:/var/lib/postgresql/data"
        networks:
            - finance-network

    worker:
        container_name: django
        command: bash -c "./wait-for-it.sh db:5432 -- && python manage.py migrate --settings="backend.settings.dev" && python manage.py runserver 0.0.0.0:8000 --settings="backend.settings.dev""
        build: ./backend
        volumes:
            - "./backend:/usr/src/finance"
        links:
            - db:db
        depends_on:
            - db
        networks:
            - finance-network
        ports:
            - 8000:8000

    web:
        container_name: react
        build: ./frontend
        volumes:
            - "./frontend:/usr/src/finance"
        env_file:
            - ./frontend/.env
        networks:
            - finance-network
        ports:
            - 8080:5100

volumes:
    postgres-data:

networks:
    finance-network:
