version: '3'

services:

    db:
        image: postgres
        container_name: postgresDB
        env_file:
            - ./db/.env
        volumes:
            - "postgres-data:/var/lib/postgresql/data"
        networks:
            - finance-network

    worker:
        container_name: django
        command: bash -c "./wait-for-it.sh db:5432 -- && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        build: ./backend
        environment: 
            - PYTHONUNBUFFERED=1
            - DJANGO_DEBUG_DOCKER=True
        volumes:
            - "./backend:/usr/src/finance"
        links:
            - db:db
        depends_on:
            - db
        networks:
            - finance-network
        ports:
            - 9090:8000

    web:
        container_name: react
        build: ./frontend
        volumes:
            - "./frontend:/usr/src/finance"
        env_file:
            - ./frontend/.env
        ports:
            - 8080:5100

volumes:
    postgres-data:

networks:
    finance-network:
